---
- name: Configure devices
  hosts: machines   # run play on group "machines"
  gather_facts: no  # do not collect system info

  tasks:
    - name: Assign node interfaces
      ansible.builtin.command: >
        docker exec clab-simple-ip-lab-{{ item.key }} sh -c "
          ip link set lo up &&
          
          {% if item.value.loopback is defined %} 
            ip addr replace {{ item.value.loopback }}/32 dev lo &&
          {% endif %}

          {% for interface, ip_addr in item.value.interfaces.items() %}
            ip link set {{ interface }} up &&
            ip addr replace {{ ip_addr }} dev {{ interface }}
          {% endfor %}
        "
      # pipe devices to dict2items for key-value conversion
      loop: "{{ devices | dict2items }}"  